//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  packages: Packages;
  packagesConnection: PackagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPackagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPackagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PackagesFilter>;
};

export type DocumentFilter = {
  packages?: InputMaybe<PackagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Packages | Folder;

export type PackagesStats = {
  __typename?: 'PackagesStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type PackagesPackages = {
  __typename?: 'PackagesPackages';
  title?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  includes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type PackagesFaqs = {
  __typename?: 'PackagesFaqs';
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Packages = Node & Document & {
  __typename?: 'Packages';
  heroTitle: Scalars['String']['output'];
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<PackagesStats>>>;
  packages?: Maybe<Array<Maybe<PackagesPackages>>>;
  faqs?: Maybe<Array<Maybe<PackagesFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PackagesStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PackagesPackagesFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  includes?: InputMaybe<StringFilter>;
};

export type PackagesFaqsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type PackagesFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  stats?: InputMaybe<PackagesStatsFilter>;
  packages?: InputMaybe<PackagesPackagesFilter>;
  faqs?: InputMaybe<PackagesFaqsFilter>;
};

export type PackagesConnectionEdges = {
  __typename?: 'PackagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Packages>;
};

export type PackagesConnection = Connection & {
  __typename?: 'PackagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PackagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePackages: Packages;
  createPackages: Packages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePackagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PackagesMutation;
};


export type MutationCreatePackagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PackagesMutation;
};

export type DocumentUpdateMutation = {
  packages?: InputMaybe<PackagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  packages?: InputMaybe<PackagesMutation>;
};

export type PackagesStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PackagesPackagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  includes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PackagesFaqsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type PackagesMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<PackagesStatsMutation>>>;
  packages?: InputMaybe<Array<InputMaybe<PackagesPackagesMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<PackagesFaqsMutation>>>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PackagesStatsFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type PackagesPackagesFilter = {
  title?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  badge?: StringFilter | null | undefined;
  icon?: StringFilter | null | undefined;
  includes?: StringFilter | null | undefined;
};

export type PackagesFaqsFilter = {
  q?: StringFilter | null | undefined;
  a?: StringFilter | null | undefined;
};

export type PackagesFilter = {
  heroTitle?: StringFilter | null | undefined;
  heroSubtitle?: StringFilter | null | undefined;
  heroBadge?: StringFilter | null | undefined;
  heroImage?: ImageFilter | null | undefined;
  stats?: PackagesStatsFilter | null | undefined;
  packages?: PackagesPackagesFilter | null | undefined;
  faqs?: PackagesFaqsFilter | null | undefined;
};

export type PackagesPartsFragment = { __typename: 'Packages', heroTitle: string, heroSubtitle: string | null, heroBadge: string | null, heroImage: string | null, stats: Array<{ __typename: 'PackagesStats', value: string | null, label: string | null } | null> | null, packages: Array<{ __typename: 'PackagesPackages', title: string | null, price: string | null, tagline: string | null, category: string | null, badge: string | null, icon: string | null, includes: Array<string | null> | null } | null> | null, faqs: Array<{ __typename: 'PackagesFaqs', q: string | null, a: string | null } | null> | null };

export type PackagesQueryVariables = Exact<{
  relativePath: string;
}>;


export type PackagesQuery = { packages: { __typename: 'Packages', id: string, heroTitle: string, heroSubtitle: string | null, heroBadge: string | null, heroImage: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'PackagesStats', value: string | null, label: string | null } | null> | null, packages: Array<{ __typename: 'PackagesPackages', title: string | null, price: string | null, tagline: string | null, category: string | null, badge: string | null, icon: string | null, includes: Array<string | null> | null } | null> | null, faqs: Array<{ __typename: 'PackagesFaqs', q: string | null, a: string | null } | null> | null } };

export type PackagesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PackagesFilter | null | undefined;
}>;


export type PackagesConnectionQuery = { packagesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Packages', id: string, heroTitle: string, heroSubtitle: string | null, heroBadge: string | null, heroImage: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats: Array<{ __typename: 'PackagesStats', value: string | null, label: string | null } | null> | null, packages: Array<{ __typename: 'PackagesPackages', title: string | null, price: string | null, tagline: string | null, category: string | null, badge: string | null, icon: string | null, includes: Array<string | null> | null } | null> | null, faqs: Array<{ __typename: 'PackagesFaqs', q: string | null, a: string | null } | null> | null } | null } | null> | null } };

export const PackagesPartsFragmentDoc = gql`
    fragment PackagesParts on Packages {
  __typename
  heroTitle
  heroSubtitle
  heroBadge
  heroImage
  stats {
    __typename
    value
    label
  }
  packages {
    __typename
    title
    price
    tagline
    category
    badge
    icon
    includes
  }
  faqs {
    __typename
    q
    a
  }
}
    `;
export const PackagesDocument = gql`
    query packages($relativePath: String!) {
  packages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PackagesParts
  }
}
    ${PackagesPartsFragmentDoc}`;
export const PackagesConnectionDocument = gql`
    query packagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PackagesFilter) {
  packagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PackagesParts
      }
    }
  }
}
    ${PackagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      packages(variables: PackagesQueryVariables, options?: C): Promise<{data: PackagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesQueryVariables, query: string}> {
        return requester<{data: PackagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesQueryVariables, query: string}, PackagesQueryVariables>(PackagesDocument, variables, options);
      },
    packagesConnection(variables?: PackagesConnectionQueryVariables, options?: C): Promise<{data: PackagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesConnectionQueryVariables, query: string}> {
        return requester<{data: PackagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PackagesConnectionQueryVariables, query: string}, PackagesConnectionQueryVariables>(PackagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  